services:
  #PostgreSQL 
  postgres:
    build:
      context: ./apps/db
      dockerfile: Dockerfile
    container_name: ufroom_postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ufroom_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ufroomUser -d ufroomdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  # API Backend
  # api:
  #   build:
  #     context: ./apps/api
  #     dockerfile: Dockerfile
  #   container_name: ufroom_api
  #   restart: unless-stopped
  #   ports:
  #     - "3001:3000"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   environment:
  #     - DATABASE_URL=postgresql://ufroomUser:ufroompassword@postgres:5432/ufroomdb
  #     - NODE_ENV=development
  #   networks:
  #     - ufroom_network

  # Frontend Web 
  # web:
  #   build:
  #     context: ./apps/web
  #     dockerfile: Dockerfile
  #   container_name: ufroom_web
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - api
  #   networks:
  #     - ufroom_network

volumes:
  postgres_data:
    driver: local

networks:
  ufroom_network:
    driver: bridge
